@echo off
echo ============================================
echo Find Android SDK Location
echo ============================================
echo.
echo Searching common locations...
echo.

set FOUND=0

REM Check common locations
set LOC1=C:\Users\%USERNAME%\AppData\Local\Android\Sdk
set LOC2=C:\Android\Sdk
set LOC3=C:\Program Files\Android\Sdk
set LOC4=C:\Program Files (x86)\Android\Sdk
set LOC5=%LOCALAPPDATA%\Android\Sdk

echo Checking: %LOC1%
if exist "%LOC1%\platform-tools" (
    echo ✓ FOUND: %LOC1%
    set FOUND=1
    set SDK_PATH=%LOC1%
)

echo Checking: %LOC2%
if exist "%LOC2%\platform-tools" (
    echo ✓ FOUND: %LOC2%
    set FOUND=1
    set SDK_PATH=%LOC2%
)

echo Checking: %LOC3%
if exist "%LOC3%\platform-tools" (
    echo ✓ FOUND: %LOC3%
    set FOUND=1
    set SDK_PATH=%LOC3%
)

echo Checking: %LOC4%
if exist "%LOC4%\platform-tools" (
    echo ✓ FOUND: %LOC4%
    set FOUND=1
    set SDK_PATH=%LOC4%
)

echo Checking: %LOC5%
if exist "%LOC5%\platform-tools" (
    echo ✓ FOUND: %LOC5%
    set FOUND=1
    set SDK_PATH=%LOC5%
)

echo.
echo ============================================

if %FOUND%==1 (
    echo.
    echo ✅ Android SDK Found!
    echo.
    echo Location: %SDK_PATH%
    echo.
    echo Now updating android\local.properties...
    echo.
    
    REM Escape backslashes for properties file
    set "ESCAPED_PATH=%SDK_PATH:\=\\%"
    
    REM Create local.properties with the found SDK path
    (
        echo ## This file is automatically generated
        echo # Location of the Android SDK
        echo sdk.dir=%ESCAPED_PATH%
    ) > android\local.properties
    
    echo ✓ android\local.properties updated!
    echo.
    echo ============================================
    echo NEXT STEP:
    echo ============================================
    echo.
    echo Run: BUILD-APK-NOW.bat
    echo.
) else (
    echo.
    echo ❌ Android SDK Not Found!
    echo.
    echo Please install Android Studio first:
    echo https://developer.android.com/studio
    echo.
    echo Or if already installed, manually edit:
    echo android\local.properties
    echo.
    echo Add this line (with your SDK path):
    echo sdk.dir=C:\\Users\\YourUsername\\AppData\\Local\\Android\\Sdk
    echo.
)

echo.
pause

